# Generated by Django 4.2.4 on 2023-11-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber')], default='electrician', max_length=20),
        ),
    ]
