# Generated by Django 4.1 on 2024-01-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='types',
            field=models.CharField(choices=[('service', 'Service'), ('product', 'Product')], default='service', max_length=20),
        ),
    ]
