<<<<<<< HEAD
# Generated by Django 4.1 on 2024-01-21 12:27
=======
# Generated by Django 4.2.7 on 2024-01-21 12:27
>>>>>>> f8979264ac2320775c5df30a5bec37ff3664587b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0005_service_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='photo',
            field=models.ImageField(default='none.jpg', upload_to='service_photos/'),
        ),
    ]
