# Generated by Django 4.1 on 2024-01-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0006_cart_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='photo',
        ),
    ]
