# Generated by Django 4.2.7 on 2024-01-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0007_alter_booking_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber')], default='electrician', max_length=20)),
                ('types', models.CharField(choices=[('service', 'Service'), ('product', 'Product')], default='product', max_length=20)),
                ('rating', models.FloatField()),
                ('total_reviews', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='product_photos/')),
            ],
        ),
    ]
