# Generated by Django 4.2.7 on 2024-01-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0008_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('product', 'Product')], default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='types',
            field=models.CharField(choices=[('service', 'Service')], default='service', max_length=20),
        ),
    ]
