# Generated by Django 5.0.1 on 2024-02-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0007_remove_cart_photo'),
        ('service_platform', '0009_alter_product_types_alter_service_types'),
    ]

    operations = [
    ]
