# Generated by Django 4.2.7 on 2024-01-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0007_remove_cart_photo'),
        ('service_platform', '0009_alter_product_types_alter_service_types'),
    ]

    operations = [
    ]
