# Generated by Django 5.0.1 on 2024-02-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0010_merge_20240205_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='service',
            name='types',
            field=models.CharField(choices=[('service', 'Service'), ('product', 'Product')], default='service', max_length=20),
        ),
    ]
