# Generated by Django 5.0.1 on 2024-03-14 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service_platform", "0010_merge_20240128_1804"),
        ("service_platform", "0012_cart_ispaid"),
    ]

    operations = []
