# Generated by Django 5.0.1 on 2024-03-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_platform", "0014_booking_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="job",
            field=models.CharField(
                choices=[("electrician", "Electrician"), ("plumber", "Plumber")],
                default="electrician",
                max_length=20,
            ),
        ),
    ]
